import React,{useState} from 'react';
import {addMonths,startOfMonth,format} from 'date-fns';
import {uk} from 'date-fns/locale';
import PublicationCalendarGrid from '@/components/studio/PublicationCalendarGrid';
import CampaignDayActions from '@/components/campaigns/CampaignDayActions';
export default function CampaignCalendar({campaign,items,onSelect,busy,action}){
 const [selected,setSelected]=useState(()=>new Date(campaign.config.start_date+'T12:00:00'));const [month,setMonth]=useState(()=>startOfMonth(selected));const [rubric,setRubric]=useState('');
 const choose=d=>{setSelected(d);setMonth(startOfMonth(d));};const filtered=items.filter(i=>!rubric||i.rubric===rubric);
 const rows=filtered.map(i=>({...i,scheduled_at:i.scheduled_local+':00',mode:'schedule',title_snapshot:i.content?.title||`Ролик ${i.sequence+1}`,account_name:i.rubric}));
 const day=format(selected,'yyyy-MM-dd'),daily=filtered.filter(i=>i.scheduled_local.slice(0,10)===day);
 return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><button className="studio-button" aria-label="Попередній місяць" onClick={()=>choose(addMonths(month,-1))}>←</button><h2 className="capitalize font-semibold">{format(month,'LLLL yyyy',{locale:uk})}</h2><button className="studio-button" aria-label="Наступний місяць" onClick={()=>choose(addMonths(month,1))}>→</button></div><label className="studio-field">Рубрика<select className="studio-input" value={rubric} onChange={e=>setRubric(e.target.value)}><option value="">Усі рубрики</option>{[...new Set(items.map(i=>i.rubric))].map(r=><option key={r} value={r}>{r}</option>)}</select></label></div><p className="text-xs text-muted-foreground">Час кампанії: {campaign.config.timezone}. Відеоплани ще не є публікаціями в Postiz.</p><PublicationCalendarGrid month={month} selected={selected} rows={rows} onSelect={choose} loading={false}/><h3 className="font-semibold">{format(selected,'d MMMM',{locale:uk})} · {daily.length} роликів</h3><div className="grid md:grid-cols-2 gap-3">{daily.map(i=><button className="panel p-4 text-left space-y-2 hover:bg-accent" key={i.id} onClick={()=>onSelect(i.id)}><span className="text-xs text-primary">{i.scheduled_local.slice(11)} · {i.rubric}</span><strong className="block text-sm">{i.content?.title||`Ролик ${i.sequence+1}`}</strong><span className="block text-xs text-muted-foreground">{i.video_id?'Передано до майстерні':i.state==='ready'?'Сценарій готовий':'Очікує сценарію'}{i.manual_edit?' · Ручні правки захищені':''}</span></button>)}</div>{!daily.length&&<p className="text-sm text-muted-foreground">На цей день поки немає роликів у вибраній рубриці. Календар наповнюється після збереження стратегії.</p>}<CampaignDayActions day={day} rubric={rubric} busy={busy} action={action}/></section>;
}