import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import CampaignSceneEditor from '@/components/campaigns/CampaignSceneEditor';
export default function CampaignItemEditor({item,campaign,busy,action,onClose}){
 const [content,setContent]=useState(item.content||null),[local,setLocal]=useState(item.scheduled_local),[meta,setMeta]=useState({rubric:item.rubric,series:item.series,format:item.format});
 const [saved,setSaved]=useState(false);const set=(key,v)=>{setSaved(false);setContent({...content,[key]:v});};
 const submit=async e=>{e.preventDefault();const result=await action('edit',{itemId:item.id,revision:item.revision,content,local,...meta});if(result)setSaved(true);};
 const regenerate=async()=>{if(window.confirm('Перегенерувати лише цей сценарій за нову платну операцію? Поточна версія буде збережена як попередня; інші сценарії й ручні правки залишаться незмінними.')){if(await action('regenerate',{itemId:item.id,revision:item.revision,confirmed:true}))onClose();}};
 return <section className="panel p-4 sm:p-5 space-y-4"><div className="flex gap-3 justify-between"><h3 className="font-semibold">Ролик {item.sequence+1}</h3><button type="button" className="studio-button" onClick={onClose}>Закрити</button></div>{item.video_id&&<p className="text-sm">Це знімок переданого сценарію. <Link className="text-primary underline" to={`/studio?id=${item.video_id}`}>Відкрити актуальну версію в майстерні</Link></p>}{!content?<p className="text-sm text-muted-foreground">Сценарій ще готується. {item.message}</p>:<form onSubmit={submit} className="space-y-4"><fieldset disabled={busy||!!item.video_id||item.state!=='ready'} className="space-y-4"><label className="studio-field">Час ({campaign.config.timezone})<input className="studio-input" required type="datetime-local" value={local} onChange={e=>setLocal(e.target.value)}/></label>{['rubric','series','format'].map((key,i)=><label key={key} className="studio-field">{['Рубрика','Серія','Формат'][i]}<input className="studio-input" required maxLength={180} value={meta[key]} onChange={e=>setMeta({...meta,[key]:e.target.value})}/></label>)}{['title','hook','ending'].map((key,i)=><label key={key} className="studio-field">{['Назва','Сильний початок','Завершення'][i]}<input className="studio-input" required maxLength={key==='title'?180:500} value={content[key]} onChange={e=>set(key,e.target.value)}/></label>)}<details><summary className="text-sm cursor-pointer">Повний текст озвучки ({content.scenes?.reduce((n,s)=>n+s.seconds,0)} с)</summary><p className="text-sm whitespace-pre-wrap mt-3">{content.scenes?.map(s=>s.narration).filter(Boolean).join('\n')}</p></details><CampaignSceneEditor scenes={content.scenes||[]} onChange={v=>set('scenes',v)} disabled={busy||!!item.video_id}/>{Object.entries(content.captions||{}).map(([platform,text])=><label key={platform} className="studio-field">Опис · {platform}<textarea className="studio-input" required rows={3} maxLength={['instagram','tiktok'].includes(platform)?2200:5000} value={text} onChange={e=>set('captions',{...content.captions,[platform]:e.target.value})}/></label>)}<p className="text-xs text-muted-foreground">Озвучка складається з текстів сцен. При зміні початку або завершення оновіть також відповідну сцену.</p><button type="submit" className="studio-button primary">{busy?'Збереження…':'Зберегти ручні правки'}</button></fieldset>{saved&&<p role="status" className="text-sm text-primary">Правки збережено.</p>}</form>}
  {!item.video_id&&item.state==='ready'&&<div className="flex flex-wrap gap-2"><button type="button" className="studio-button" disabled={busy||!!campaign.worker_token} onClick={regenerate}>Перегенерувати лише цей</button><button type="button" className="studio-button" disabled={busy||!!campaign.worker_token} onClick={async()=>{await action('export',{itemId:item.id});}}>Передати до майстерні</button></div>}
  {item.previous_content?.script&&<details><summary className="text-xs cursor-pointer">Попередня збережена озвучка</summary><p className="text-xs whitespace-pre-wrap mt-3">{item.previous_content.script}</p></details>}
 </section>;
}