import React from 'react';
import {RefreshCw,Play,Clock3} from 'lucide-react';
const date=value=>value?new Date(/(?:Z|[+-]\d{2}:\d{2})$/i.test(value)?value:value+'Z'):null;
const stamp=value=>date(value)?.toLocaleString('uk-UA')||'Ще не було';
export default function CampaignProcessStatus({campaign,steps,items=[],settings,busy,refreshing,action,refresh}){
 const latest=steps[0],open=steps.find(s=>['reserved','calling','uncertain','result'].includes(s.state));
 const elapsed=campaign.worker_started_at?Date.now()-date(campaign.worker_started_at).getTime():0;
 const active=!!campaign.worker_token,stale=active&&elapsed>=15*60000;
 const pending=items.filter(i=>i.state==='pending').length,ready=items.filter(i=>i.state==='ready').length;
 const phase=stale?'Крок довго не завершується':active?'Виконується поточний крок':campaign.status==='needs_attention'?'Зупинено перевіркою результату':campaign.status==='budget_paused'?'Очікує зміни бюджету':campaign.status==='running'?(settings?.operation_lock?'Очікує іншу операцію студії':settings?.generation_paused?'Загальна генерація на паузі':'Очікує наступного фонового циклу'):({paused:'На паузі',completed:'Завершено',draft:'Ще не запущено',stopped:'Остаточно зупинено'}[campaign.status]||campaign.status);
 const next=()=>{if(window.confirm('Виконати один крок зараз замість очікування розкладу? Можливий один платний запит у межах лімітів; готові сценарії не повторюватимуться.'))action('tick');};
 return <div className="rounded-lg border border-border bg-background p-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-sm font-medium flex items-center gap-2"><Clock3 size={16}/>{phase}</h3><button type="button" className="studio-button" disabled={busy||refreshing} onClick={refresh}><RefreshCw size={14}/>Оновити стан</button></div><dl className="grid sm:grid-cols-3 gap-3 text-xs"><div><dt className="text-muted-foreground">Готові / очікують</dt><dd className="mt-1">{ready} / {pending}{items.length<campaign.total_count?' · календар ще готується':''}</dd></div><div><dt className="text-muted-foreground">Остання спроба</dt><dd className="mt-1">{stamp(campaign.worker_started_at)}</dd></div><div><dt className="text-muted-foreground">Останнє оновлення кроку</dt><dd className="mt-1">{stamp(latest?.updated_date)}</dd></div></dl>{open&&<p className="text-xs text-muted-foreground">{open.result?'Відповідь ШІ збережена: спочатку відновіть її без нового платного запиту.':'Результат запиту ще не підтверджено: повторна оплата можлива лише після окремого дозволу.'}</p>}{campaign.status==='running'&&!active&&elapsed>10*60000&&<p className="text-xs text-muted-foreground">Понад 10 хвилин не було нової спроби; можна запустити один крок вручну, якщо студія вільна.</p>}{stale&&<p className="text-xs text-destructive">Минуло понад 15 хвилин: скористайтеся відновленням нижче, не перезапускайте всю кампанію.</p>}{campaign.status==='running'&&<button type="button" className="studio-button" disabled={busy||active||!!open||!!settings?.operation_lock||!!settings?.generation_paused} onClick={next}><Play size={14}/>Виконати один крок зараз</button>}<p className="text-xs text-muted-foreground">Стан оновлюється кожні 15 секунд · фоновий розклад — кожні 5 хвилин · до 2 сценаріїв за крок · час вашого браузера.</p></div>;
}