import React,{useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import CampaignFields from '@/components/campaigns/CampaignFields';
import CampaignAdBudget from '@/components/campaigns/CampaignAdBudget';
import CampaignEstimate from '@/components/campaigns/CampaignEstimate';
export default function CampaignForm({onCreated,onCancel}){
 const [name,setName]=useState('Контент на місяць');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [value,setValue]=useState({brief:'Створи контент на 30 днів, по 5 відео щодня, на тему таро, астрології та стосунків, із просуванням Telegram-бота @AITarotist_bot',topic:'Таро, астрологія та стосунки',goal:'Залучення аудиторії та переходи до Telegram-бота',audience:'Доросла аудиторія, зацікавлена у самопізнанні та стосунках',language:'uk',start_date:new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw'}).format(new Date()),days:30,per_day:5,timezone:'Europe/Warsaw',account_ids:[],duration:30,voice:'river',visual_style:'Містична редакційна ілюстрація, темно-фіолетові тони, стримане золото',ad_every:3,ad_seconds:3,ad_position:'end',ad_text:'@AITarotist_bot — твій особистий розклад',daily_limit:100,monthly_limit:1000,video_limit:35,times_text:'09:00, 12:00, 15:00, 18:00, 21:00'});
 const {data:settings=[],isLoading,error:accountError}=useQuery({queryKey:['campaign-account-settings'],queryFn:()=>base44.entities.StudioSettings.list('created_date',1)});const accounts=(settings[0]?.postiz_accounts||[]).filter(a=>!a.disabled&&['instagram','instagram-standalone','tiktok','youtube','facebook'].includes(a.platform));
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const {data}=await base44.functions.invoke('campaignControl',{action:'create',name,config:{...value,times:value.times_text.split(',').map(t=>t.trim())}});if(data.error)throw new Error(data.error);onCreated(data.id);}catch(e){setError(e.response?.data?.error||e.message);}finally{setBusy(false);}};
 return <form onSubmit={submit} className="panel p-4 sm:p-6 space-y-6"><h2 className="text-lg font-semibold">Нова кампанія</h2><fieldset disabled={busy} className="space-y-4"><label className="studio-field">Назва<input className="studio-input" required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="studio-field">Завдання для ШІ<textarea className="studio-input" required maxLength={3000} rows={3} value={value.brief} onChange={e=>setValue({...value,brief:e.target.value})}/><span className="text-xs text-muted-foreground">Параметри нижче визначають кількість, розклад і бюджет; текст завдання задає творчий напрям.</span></label></fieldset><CampaignFields value={value} onChange={setValue} disabled={busy}/>
  <fieldset disabled={busy} className="space-y-3"><legend className="text-sm font-semibold mb-3">Акаунти для майбутніх публікацій</legend>{isLoading?<p className="text-xs">Завантаження…</p>:accountError?<p role="alert" className="text-xs text-destructive">Не вдалося завантажити збережені акаунти.</p>:accounts.length?accounts.map(a=><label key={a.id} className="flex items-center gap-3 min-h-11 text-sm"><input type="checkbox" checked={value.account_ids.includes(a.id)} onChange={e=>setValue({...value,account_ids:e.target.checked?[...value.account_ids,a.id]:value.account_ids.filter(id=>id!==a.id)})}/>{a.name} · {a.platform}</label>):<p className="text-xs text-muted-foreground">Акаунтів у збереженому списку немає. Можна підготувати сценарії без них; для публікації підключіть акаунти в Postiz і оновіть їх у студії.</p>}</fieldset>
  <CampaignAdBudget value={value} onChange={setValue} disabled={busy}/><CampaignEstimate config={value}/>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap gap-3"><button className="studio-button primary" disabled={busy||value.days*value.per_day>300}>{busy?'Збереження…':'Зберегти кампанію без запуску'}</button><button type="button" className="studio-button" onClick={onCancel} disabled={busy}>Скасувати</button></div>{value.days*value.per_day>300&&<p className="text-xs text-destructive">Максимум 300 унікальних відео в одній кампанії.</p>}</form>;
}