import React,{useEffect,useState} from 'react';
import CampaignProcessStatus from '@/components/campaigns/CampaignProcessStatus';
export default function CampaignControls({campaign,steps,usage,items,settings,busy,action,refresh,refreshing}){
 const open=steps.find(s=>['reserved','calling','uncertain','result'].includes(s.state));
 const started=open&&['reserved','calling'].includes(open.state)?open.created_date:campaign.worker_token?campaign.worker_started_at:null;
 const recoveryWait=started?Math.max(0,15-Math.floor((Date.now()-new Date(/(?:Z|[+-]\d{2}:\d{2})$/i.test(started)?started:started+'Z').getTime())/60000)):0;
 const [daily,setDaily]=useState(campaign.config.daily_limit),[monthly,setMonthly]=useState(campaign.config.monthly_limit);
 useEffect(()=>{setDaily(campaign.config.daily_limit);setMonthly(campaign.config.monthly_limit);},[campaign.config.daily_limit,campaign.config.monthly_limit]);
 const labels={draft:'Чернетка',running:'Підготовка у фоні',paused:'Пауза',budget_paused:'Пауза через бюджет',needs_attention:'Потрібне рішення',completed:'Сценарії готові',stopped:'Зупинено'};
 const start=()=>{if(window.confirm('Дозволити платну підготовку стратегії та всіх сценаріїв у межах оцінкових лімітів? Це не запускає відеовиробництво чи публікацію.'))action(campaign.status==='draft'?'start':'resume',{confirmed:true});};
 const retry=()=>{if(window.confirm('Дозволити нову платну спробу незавершеного кроку? Попередній результат може бути оплачений; його оцінка залишається в обліку. Уже готові сценарії не перегенеруються.'))action('recover',{retry:true,confirmed:true});};
 return <section className="panel p-5 space-y-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Керування процесом · {labels[campaign.status]||campaign.status}</h2><span className="text-sm">{campaign.ready_count||0} / {campaign.total_count} сценаріїв</span></div><progress className="w-full h-2 accent-primary" value={campaign.ready_count||0} max={campaign.total_count} aria-label="Готовність сценаріїв"/><p className="text-sm text-muted-foreground" role="status">{campaign.message}</p><CampaignProcessStatus campaign={campaign} steps={steps} items={items} settings={settings} busy={busy} refreshing={refreshing} action={action} refresh={refresh}/><div className="flex flex-wrap gap-2">
  {['draft','paused','budget_paused'].includes(campaign.status)&&<button className="studio-button primary" disabled={busy||!!campaign.worker_token} onClick={start}>{campaign.status==='draft'?'Запустити план і сценарії':'Продовжити'}</button>}
  {campaign.status==='running'&&<button className="studio-button" disabled={busy} onClick={()=>action('pause')}>Пауза</button>}
  {!['stopped','completed'].includes(campaign.status)&&<button className="studio-button" disabled={busy} onClick={()=>{if(window.confirm('Зупинити кампанію остаточно? Поточний запит може завершитися; збережені результати залишаться доступними.'))action('stop');}}>Зупинити</button>}
  {(campaign.status==='needs_attention'||campaign.worker_token||steps.some(s=>['result','uncertain'].includes(s.state)))&&<><button className="studio-button" disabled={busy||recoveryWait>0} onClick={()=>action('recover')}>Відновити без нової генерації</button>{campaign.status!=='stopped'&&<button className="studio-button" disabled={busy||recoveryWait>0} onClick={retry}>Дозволити нову платну спробу</button>}{recoveryWait>0&&<span className="text-xs text-muted-foreground self-center">Відновлення приблизно через {recoveryWait} хв.</span>}</>}
 </div><p className="text-xs text-muted-foreground">Фоновий цикл — кожні 5 хвилин; до двох сценаріїв за крок. Пауза й зупинка не скасовують уже надісланий платний запит. Для завислого запиту відновлення доступне через 15 хвилин.</p>
 {['draft','paused','budget_paused','needs_attention'].includes(campaign.status)&&<form className="grid sm:grid-cols-3 gap-3 items-end" onSubmit={e=>{e.preventDefault();action('budgets',{daily:Number(daily),monthly:Number(monthly)});}}><label className="studio-field">Кредитів / день (UTC)<input className="studio-input" required type="number" min="1" max="100000" value={daily} onChange={e=>setDaily(e.target.value)}/></label><label className="studio-field">Кредитів / місяць (UTC)<input className="studio-input" required type="number" min="1" max="1000000" value={monthly} onChange={e=>setMonthly(e.target.value)}/></label><button className="studio-button" disabled={busy||!!campaign.worker_token}>Зберегти ліміти</button></form>}
 {campaign.regenerate_item_id&&<p className="text-sm text-primary">У черзі — перегенерація лише вибраного сценарію; після неї відновиться попередній режим кампанії.</p>}
 <p className="text-xs text-muted-foreground">Зарезервовано за оцінкою Base44: {usage?.total||0} кр. за кампанію · {usage?.day||0} сьогодні · {usage?.month||0} цього місяця (UTC). Невідомі результати також враховано.</p>
 <details><summary className="text-xs cursor-pointer">Останні 10 кроків</summary><div className="space-y-2 mt-3">{!steps.length?<p className="text-xs">Ще немає виконаних кроків.</p>:steps.map(s=><p key={s.id} className="text-xs border-t border-border pt-2">{s.kind==='strategy'?'Стратегія':'Порція сценаріїв'} · {{reserved:'Зарезервовано',calling:'ШІ працює',result:'Відповідь збережено',completed:'Завершено',uncertain:'Результат невідомий',abandoned:'Повтор погоджено'}[s.state]||s.state}<span className="block text-muted-foreground mt-1">{new Date(/(?:Z|[+-]\d{2}:\d{2})$/i.test(s.created_date)?s.created_date:s.created_date+'Z').toLocaleString('uk-UA')}{s.item_ids?.length?` · Сценарії: ${s.item_ids.map(id=>(items||[]).find(i=>i.id===id)?.sequence+1).join(', ')}`:''}</span><span className="block text-muted-foreground mt-1">{s.message}</span></p>)}</div></details></section>;
}