import React,{useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import CampaignForm from '@/components/campaigns/CampaignForm';
import CampaignWorkspace from '@/components/campaigns/CampaignWorkspace';
export default function ContentCampaigns(){
 const [params,setParams]=useSearchParams(),id=params.get('id');const [creating,setCreating]=useState(false),qc=useQueryClient();
 const {data:campaigns=[],isLoading,error,refetch}=useQuery({queryKey:['content-campaigns'],refetchInterval:15000,queryFn:async()=>{let rows=[],page;do{page=await base44.entities.ContentCampaign.list('-created_date',100,rows.length);rows.push(...page);}while(page.length===100);return rows;}});
 if(id)return <CampaignWorkspace key={id} id={id}/>;
 if(creating)return <CampaignForm onCancel={()=>setCreating(false)} onCreated={newId=>{setCreating(false);qc.invalidateQueries({queryKey:['content-campaigns']});setParams({id:newId});}}/>;
 const labels={draft:'Чернетка',running:'Підготовка у фоні',paused:'Пауза',budget_paused:'Пауза через бюджет',needs_attention:'Потрібне рішення',completed:'Сценарії готові',stopped:'Зупинено'};
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold">Контент на місяць</h1><p className="text-sm text-muted-foreground mt-2">Стратегія, готові сценарії та календар · до 300 унікальних роликів у кампанії.</p></div><button className="studio-button primary" onClick={()=>setCreating(true)}>Нова кампанія</button></div><p className="panel p-4 text-sm text-muted-foreground">Доступний режим «Лише план і сценарії»: фонова підготовка після підтвердження запуску, без автоматичного виробництва чи публікації відео.</p>{error?<div role="alert" className="panel p-5"><p className="text-destructive">Не вдалося завантажити кампанії.</p><button className="studio-button mt-3" onClick={()=>refetch()}>Повторити</button></div>:isLoading?<p className="panel p-8">Завантаження…</p>:!campaigns.length?<div className="panel p-8 text-center space-y-3"><h2 className="font-semibold">Кампаній ще немає</h2><p className="text-sm text-muted-foreground">Задайте тему, кількість роликів і розклад. Чернетка зберігається без витрат на генерацію.</p><button className="studio-button" onClick={()=>setCreating(true)}>Створити першу кампанію</button></div>:<div className="grid md:grid-cols-2 gap-4">{campaigns.map(c=><Link key={c.id} to={`/campaigns?id=${c.id}`} className="panel p-5 space-y-3 hover:bg-accent"><div className="flex justify-between gap-3"><h2 className="font-semibold break-words">{c.name}</h2><span className="text-xs text-primary">{labels[c.status]||c.status}</span></div><p className="text-sm text-muted-foreground">{c.total_count} відео · {c.total_count*(c.config?.account_ids?.length||0)} потенційних публікацій</p><p className="text-xs">{c.config?.start_date} · {c.config?.timezone} · Готово {c.ready_count||0}/{c.total_count}</p>{c.message&&<p className={`text-xs ${c.status==='needs_attention'?'text-destructive':'text-muted-foreground'}`}>{c.message}</p>}<span className="inline-block text-sm text-primary">Керувати процесом</span></Link>)}</div>}</div>;
}