import React, {useState} from 'react';
import { Link } from 'react-router-dom';
import { Plus, Sparkles, Pause, Play, ArrowRight, CircleHelp } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import useStudioData from '@/components/studio/useStudioData';
import TarotArtwork from '@/components/studio/TarotArtwork';
import TemplateGallery from '@/components/studio/TemplateGallery';
import DashboardStats from '@/components/studio/DashboardStats';
import IntegrationSummary from '@/components/studio/IntegrationSummary';
import VideoList from '@/components/studio/VideoList';
export default function Dashboard(){
 const {videos,settings,operations,loading,error,refresh}=useStudioData();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const toggle=async()=>{setBusy(true);setMessage('');try{await base44.entities.StudioSettings.update(settings.id,{generation_paused:!settings.generation_paused});await refresh();}catch{setMessage('Не вдалося змінити стан. Спробуйте ще раз.');}finally{setBusy(false);}};
 return <div className="space-y-7"><div className="flex justify-between items-start gap-4"><div><div className="text-[10px] tracking-[.17em] text-muted-foreground mb-2">ВАША ТВОРЧА ОРБІТА</div><h1 className="text-2xl md:text-[28px] font-semibold tracking-tight">Місце, де ідеї стають відео</h1><p className="mt-2 text-xs text-muted-foreground">Створюйте зі змістом. Публікуйте у своєму ритмі.</p></div><Link to="/studio" className="studio-button primary shrink-0"><Plus size={16}/><span className="hidden sm:inline">Створити відео</span></Link></div>{(message||error)&&<div role="alert" className="studio-alert">{message||'Не вдалося завантажити студію. Оновіть сторінку.'}</div>}<section className="studio-hero"><div className="p-7 md:p-8 flex-1"><span className="inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-300/5 px-3 py-1.5 text-[9px] tracking-wider text-violet-200"><Sparkles size={12}/>ВІД ІДЕЇ ДО ВЛАСНОЇ ІСТОРІЇ</span><h2 className="text-2xl md:text-[29px] leading-tight font-medium tracking-tight mt-4">Ваша наступна історія<br/><span className="text-violet-300">починається тут.</span></h2><p className="text-[11px] text-[#aca2bd] mt-3 max-w-md leading-relaxed">Таро, зірки, почуття та маленькі відкриття.<br/>Перетворіть одну ідею на контент, який відгукується.</p><Link to="/studio" className="studio-button primary mt-5">Створити перший матеріал<ArrowRight size={14}/></Link></div><TarotArtwork/></section><DashboardStats videos={videos} operations={operations}/><TemplateGallery/><div className="grid xl:grid-cols-[1fr_310px] gap-5"><section><div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-4"><div className="flex gap-2 items-center"><h2 className="text-sm font-semibold">Черга створення</h2><span className="status-tag">{videos.length}</span></div><div className="flex flex-wrap items-center gap-4"><button className="text-xs sm:text-[10px] text-muted-foreground flex items-center gap-1.5 min-h-11 sm:min-h-0" disabled={busy||!settings} onClick={toggle}>{settings?.generation_paused?<Play size={12}/>:<Pause size={12}/>} {settings?.generation_paused?'Відновити генерацію':'Призупинити генерацію'}</button><Link className="text-xs sm:text-[10px] text-violet-300 inline-flex items-center min-h-11 sm:min-h-0" to="/library">Усі матеріали</Link></div></div><VideoList videos={videos.slice(0,4)} loading={loading}/><div className="flex items-start gap-2 text-[10px] text-muted-foreground mt-4"><CircleHelp size={13} className="shrink-0"/><span>Ручне погодження за замовчуванням. Монтаж і передача у Postiz запускаються в майстерні кожного відео.</span></div></section><IntegrationSummary/></div></div>;
}