import React, {useState,useEffect} from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import useStudioData from '@/components/studio/useStudioData';
import VideoBrief from '@/components/studio/VideoBrief';
import ScriptEditor from '@/components/studio/ScriptEditor';
import GenerationControls from '@/components/studio/GenerationControls';
import VideoPreview from '@/components/studio/VideoPreview';
import RenderControls from '@/components/studio/RenderControls';
import PublishControls from '@/components/studio/PublishControls';
const defaults={topic:'',format:'daily',language:'uk',tone:'Загадковий',duration:30,voice:'river',instructions:'',ad_enabled:true,ad_text:'Твій особистий розклад — у @AITarotist_bot',script:'',credit_limit:35};
export default function Studio(){
 const [params,setParams]=useSearchParams(); const id=params.get('id'); const {settings,refresh}=useStudioData();
 const [value,setValue]=useState({...defaults,format:params.get('format')||'daily'});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(!!id);
 useEffect(()=>{if(id){setLoading(true);base44.entities.StudioVideo.get(id).then(v=>{if(!v)throw new Error();setValue({...defaults,...v});}).catch(()=>setError('Матеріал не знайдено або доступ заборонено.')).finally(()=>setLoading(false));}},[id]);
 const save=async()=>{if(!value.topic.trim())throw new Error('Введіть тему відео.');if(!Number.isFinite(value.credit_limit)||value.credit_limit<1||value.credit_limit>1000)throw new Error('Ліміт має бути від 1 до 1000 кредитів.');if(value.format==='own'&&(!value.source_text?.trim()||!value.rights_confirmed))throw new Error('Додайте історію та підтвердьте права.');const {id:ignore,created_date,updated_date,created_by_id,created_by,...data}=value;data.title=value.title||value.topic;const previous=id?await base44.entities.StudioVideo.get(id):null;if(previous&&['running','render_pending'].includes(previous.status))throw new Error('Дочекайтеся завершення поточної операції перед редагуванням.');if(previous&&(previous.script!==value.script||previous.voice!==value.voice)){Object.assign(data,{audio_url:'',video_uri:'',approved:false,status:'script_ready'});if(previous.script!==value.script){data.scenes=[];data.hook='';}}const saved=id?await base44.entities.StudioVideo.update(id,data):await base44.entities.StudioVideo.create(data);setValue({...defaults,...saved});if(!id)setParams({id:saved.id},{replace:true});return saved;};
 const run=async(name,task)=>{setBusy(name);setError('');setNotice('');try{await task();await refresh();}catch(e){setError(e.response?.data?.error||e.message||'Не вдалося виконати дію. Спробуйте ще раз.');await refresh();}finally{setBusy(false);}};
 const generate=stage=>run(stage,async()=>{if((stage==='script'&&value.script)||(stage==='audio'&&value.audio_url)||(stage==='visual'&&value.image_url)){if(!window.confirm('Створити нову версію цього компонента? Це нова платна операція; попередня версія компонента буде замінена.'))return;}const saved=await save();const r=await base44.functions.invoke('studioGenerate',{videoId:saved.id,stage});if(r.data.error)throw new Error(r.data.error);setValue({...defaults,...await base44.entities.StudioVideo.get(saved.id)});setNotice('Новий компонент збережено.');});
 const upload=e=>{const file=e.target.files?.[0];if(!file)return;run('upload',async()=>{if(file.type!=='video/mp4'||file.size>50*1024*1024)throw new Error('Оберіть MP4 до 50 МБ.');if(!window.confirm('Підтверджуєте права на відео, зображення та музику в цьому файлі?'))return;await new Promise((resolve,reject)=>{const el=document.createElement('video');const local=URL.createObjectURL(file);el.preload='metadata';el.onloadedmetadata=()=>{URL.revokeObjectURL(local);el.videoWidth===1080&&el.videoHeight===1920?resolve():reject(new Error('Потрібен вертикальний MP4 розміром 1080 × 1920.'));};el.onerror=()=>{URL.revokeObjectURL(local);reject(new Error('Браузер не може прочитати це відео. Експортуйте MP4 з H.264 та AAC.'));};el.src=local;});const saved=await save();const {file_uri}=await base44.integrations.Core.UploadPrivateFile({file});const updated=await base44.entities.StudioVideo.update(saved.id,{video_uri:file_uri,status:'ready',approved:false});setValue({...defaults,...updated});setNotice('Готовий ролик збережено приватно.');});e.target.value='';};
 const renderAction=(action,extra)=>run('render',async()=>{const saved=action==='start'?await save():value;let seconds;if(action==='start'){seconds=await new Promise((resolve,reject)=>{const audio=new Audio();const timer=setTimeout(()=>reject(new Error('Не вдалося визначити тривалість озвучки.')),15000);audio.onloadedmetadata=()=>{clearTimeout(timer);const d=audio.duration;audio.removeAttribute('src');resolve(d);};audio.onerror=()=>{clearTimeout(timer);reject(new Error('Озвучка недоступна.'));};audio.preload='metadata';audio.src=saved.audio_url;});}const {data}=await base44.functions.invoke('studioRender',{videoId:saved.id,action,...extra,seconds,confirmed:true});if(data.error)throw new Error(data.error);setValue({...defaults,...await base44.entities.StudioVideo.get(saved.id)});setNotice(data.message||({submitted:'Монтаж виконується у Creatomate. Перевірте готовність пізніше.',succeeded:'Монтаж готовий. Перевірте та збережіть MP4 перед погодженням.',failed:'Creatomate повідомив про помилку.',uncertain:'Результат невідомий — повторний платний запуск заблоковано.'}[data.state]||'Стан монтажу оновлено.'));});
 const send=payload=>run('publish',async()=>{const saved=await save();const {data}=await base44.functions.invoke('studioPublish',{action:'send',videoId:saved.id,...payload});if(data.error)throw new Error(data.error);setNotice(data.message||(payload.mode==='draft'?'Чернетку передано у Postiz без публікації.':'Postiz прийняв запит. Перевірте статус окремою кнопкою.'));});
 const togglePublication=()=>run('pause',async()=>{await base44.entities.StudioSettings.update(settings.id,{publication_paused:!settings.publication_paused});});
 const approve=()=>run('approve',async()=>{const current=await save();if(!current.video_uri)throw new Error('Після змін потрібне нове відео.');setValue({...defaults,...await base44.entities.StudioVideo.update(current.id,{approved:true,status:'approved'})});setNotice('Погоджено. Тепер можна обрати акаунт і режим передачі у Postiz.');});
 return <div className="space-y-6"><Link to="/library" className="inline-flex gap-2 text-xs text-muted-foreground items-center"><ArrowLeft size={14}/>До бібліотеки</Link><div><h1 className="text-2xl font-semibold">{id?'Майстерня відео':'Створити нову історію'}</h1><p className="text-xs text-muted-foreground mt-2">Від теми до готових матеріалів · ручне погодження</p></div><div className="flex flex-wrap gap-2 text-[10px] text-muted-foreground">{['01 Ідея','02 Сценарій','03 Озвучка','04 Візуал','05 Монтаж','06 Postiz'].map(s=><span key={s} className="status-tag">{s}</span>)}</div>{error&&<div role="alert" className="studio-alert text-rose-200">{error}</div>}{notice&&<div role="status" className="studio-alert">{notice}</div>}{loading?<div className="p-20 flex justify-center"><Loader2 className="animate-spin"/></div>:<div className="grid lg:grid-cols-[minmax(0,1fr)_330px] gap-5 items-start"><div className="space-y-5"><VideoBrief value={value} onChange={setValue} disabled={!!busy}/><ScriptEditor value={value} onChange={setValue} disabled={!!busy}/><GenerationControls value={value} onChange={setValue} busy={busy} paused={settings?.generation_paused} onSave={()=>run('save',async()=>{await save();setNotice('Зміни збережено.');})} onGenerate={generate}/></div><div className="space-y-5"><VideoPreview video={value} busy={!!busy} onApprove={approve} onUpload={upload}/><RenderControls video={value} busy={!!busy} onAction={renderAction}/><PublishControls video={value} busy={!!busy} settings={settings} onSend={send} onPause={togglePublication}/></div></div>}</div>;
}