import React,{useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {base44} from '@/api/base44Client';
import {Upload,File,ExternalLink} from 'lucide-react';
export default function AssetLibrary(){
 const {data:assets=[],isLoading,refetch}=useQuery({queryKey:['studio-assets'],queryFn:()=>base44.entities.StudioAsset.list('-created_date',100)});const [rights,setRights]=useState(false);const [source,setSource]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [links,setLinks]=useState({});
 const upload=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{if(!rights)throw new Error('Підтвердьте права на матеріал.');if(file.size>50*1024*1024)throw new Error('Максимальний розмір — 50 МБ.');const {file_uri}=await base44.integrations.Core.UploadPrivateFile({file});await base44.entities.StudioAsset.create({name:file.name,file_uri,type:file.type,rights_confirmed:true,source_url:source});await refetch();}catch(e){setError(e.message||'Не вдалося завантажити файл.');}finally{setBusy(false);e.target.value='';}};
 const open=async id=>{setError('');setBusy(true);try{const r=await base44.functions.invoke('studioAssetAccess',{id,kind:'asset'});if(r.data.error)throw new Error(r.data.error);setLinks(prev=>({...prev,[id]:r.data.url}));}catch(e){setError(e.message||'Не вдалося відкрити файл.');}finally{setBusy(false);}};
 return <section className="panel p-5 space-y-4"><div className="flex items-center gap-2"><Upload size={17} className="text-violet-300"/><h2 className="text-sm font-semibold">Ваші матеріали</h2></div><p className="text-xs text-muted-foreground">Фони, музика, зображення, логотипи та відео. Файли зберігаються приватно; доступ до завантаження тимчасовий.</p><div className="grid md:grid-cols-2 gap-4"><label className="studio-field">Посилання на джерело або ліцензію<input className="studio-input" type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://…"/></label><label className="studio-field">Завантажити файл (до 50 МБ)<input type="file" accept="image/*,audio/*,video/mp4,text/plain" disabled={busy||!rights} onChange={upload} className="text-xs file:mr-2 file:p-3 file:rounded file:bg-violet-400/10 file:text-violet-200 file:border-0"/></label></div><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>Я маю право використовувати цей матеріал, включно з музикою.</label>{error&&<p role="alert" className="text-xs text-rose-300">{error}</p>}{busy&&<p role="status" className="text-xs text-violet-200">Обробка файлу…</p>}{isLoading?<p className="text-xs text-muted-foreground">Завантаження…</p>:!assets.length?<p className="text-xs text-muted-foreground pt-3">Ви ще не завантажили власні матеріали.</p>:assets.map(a=><div key={a.id} className="flex flex-wrap items-center gap-3 border-t border-white/[.06] pt-3"><File size={16} className="text-muted-foreground"/><span className="text-xs flex-1 min-w-[150px] truncate">{a.name}</span>{links[a.id]?<a href={links[a.id]} target="_blank" rel="noreferrer" className="studio-button text-xs">Відкрити<ExternalLink size={12}/></a>:<button disabled={busy} className="studio-button text-xs" onClick={()=>open(a.id)}>Отримати доступ</button>}</div>)}</section>;
}