import React,{useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Clapperboard,RefreshCw} from 'lucide-react';
import {base44} from '@/api/base44Client';
import useStudioConnections from '@/components/studio/useStudioConnections';
export default function RenderControls({video,busy,onAction}){
 const [musicId,setMusicId]=useState('');const {data:connections}=useStudioConnections();
 const {data:jobs=[]}=useQuery({queryKey:['studio-render',video.id],queryFn:()=>base44.entities.StudioRender.filter({video_id:video.id},'-created_date',1),enabled:!!video.id});
 const {data:assets=[]}=useQuery({queryKey:['studio-assets'],queryFn:()=>base44.entities.StudioAsset.list('-created_date',100)});const job=jobs[0];
 const start=()=>{if(window.confirm('Запустити один платний монтаж у Creatomate? Вартість і субтитри оплачуються за тарифом Creatomate та не входять у ліміт кредитів Base44.'))onAction('start',{musicId});};
 return <section className="panel p-5 space-y-4"><h2 className="text-sm font-semibold flex items-center gap-2"><Clapperboard size={16}/>Монтаж у Creatomate</h2><p className="text-xs text-muted-foreground">Зображення + озвучка + синхронізовані субтитри, MP4 1080 × 1920. Довжина відповідає озвучці, максимум 90 секунд.</p><label className="studio-field">Фонова музика з бібліотеки<select disabled={busy} className="studio-input" value={musicId} onChange={e=>setMusicId(e.target.value)}><option value="">Без музики</option>{assets.filter(a=>a.rights_confirmed&&a.type?.startsWith('audio/')).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button disabled={busy||!connections?.creatomate?.connected||!video.audio_url||!video.image_url||['reserved','submitted','uncertain'].includes(job?.state)} onClick={start} className="studio-button primary w-full">Запустити платний монтаж</button>{!connections?.creatomate?.connected&&<p className="text-xs text-muted-foreground">Спочатку перевірте підключення Creatomate в інтеграціях.</p>}{job&&<div className="border-t border-border pt-3 space-y-3"><p className="text-xs">{{reserved:'Підготовка запиту',submitted:'Монтаж запущено',succeeded:'Монтаж завершено',failed:'Помилка монтажу',uncertain:'Результат невідомий'}[job.state]}</p><p className="text-[10px] text-muted-foreground">{job.message}</p>{job.provider_id&&<><p className="text-[10px] font-mono break-all">{job.provider_id}</p><button disabled={busy} onClick={()=>onAction('check',{})} className="studio-button w-full"><RefreshCw size={13}/>Перевірити та зберегти MP4</button></>}</div>}<p className="text-[10px] text-muted-foreground">Монтаж продовжується після закриття сторінки. Поверніться й натисніть перевірку; повторного платного запуску не буде. Нова музика потребує нової версії компонентів.</p></section>;
}