import React, {useEffect,useState} from 'react';
import { Image } from '@/components/ui/image';
import { Film, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { base44 } from '@/api/base44Client';
export default function VideoPreview({video,busy,onApprove,onUpload}){
 const [url,setUrl]=useState('');const [error,setError]=useState('');
 useEffect(()=>{setUrl('');if(video.id&&video.video_uri){base44.functions.invoke('studioAssetAccess',{id:video.id,kind:'video'}).then(r=>{if(r.data.error)setError(r.data.error);else setUrl(r.data.url);}).catch(()=>setError('Не вдалося відкрити відео.'));}},[video.id,video.video_uri]);
 return <section className="panel p-5"><div className="flex justify-between text-xs mb-4"><h2 className="font-semibold">Перегляд</h2><span className="text-muted-foreground">9:16 · 1080 × 1920</span></div><div className="mx-auto aspect-[9/16] max-w-[235px] rounded-xl border border-white/10 bg-[#0b0b11] overflow-hidden relative">{url?<video src={url} controls playsInline className="w-full h-full object-contain"/>:video.image_url?<><Image src={video.image_url} className="w-full h-full" alt="Згенерований фон — ще не змонтоване відео"/><div className="absolute bottom-8 inset-x-5 text-center bg-black/70 rounded p-2 text-xs">Зображення, не готовий ролик</div></>:<div className="h-full flex flex-col items-center justify-center text-center p-5 text-muted-foreground"><Film size={30} strokeWidth={1}/><p className="text-xs mt-3">Ваше відео<br/>з’явиться тут</p><p className="text-[9px] mt-4">Без демонстраційного контенту</p></div>}</div>{error&&<p role="alert" className="text-xs text-rose-300 mt-3">{error}</p>}{video.audio_url&&<div className="mt-5"><p className="text-xs mb-2 text-muted-foreground">Готова озвучка</p><audio controls src={video.audio_url} className="w-full h-9"/></div>}<div className="mt-5 space-y-3"><p className="studio-alert">Запустіть монтаж у Creatomate нижче або завантажте власний готовий MP4. Після монтажу натисніть «Перевірити та зберегти MP4».</p><label className="studio-field">Готове відео MP4 (до 50 МБ)<input type="file" accept="video/mp4" disabled={busy||!video.id} onChange={onUpload} className="text-xs file:mr-3 file:rounded file:border-0 file:bg-violet-400/10 file:text-violet-200 file:p-2"/></label>{video.video_uri&&<button disabled={busy||video.approved} onClick={onApprove} className="studio-button primary w-full">{video.approved?'Відео погоджено':'Погодити після перегляду'}</button>}<Link to="/integrations" className="studio-button w-full"><ExternalLink size={13}/>Перевірити інтеграції</Link><p className="text-[10px] text-muted-foreground">Погодження не запускає публікацію. Передайте відео у Postiz окремою дією нижче.</p></div></section>;
}