import React from 'react';
import { Link } from 'react-router-dom';
import { Film, ArrowUpRight, Plus } from 'lucide-react';
import { Image } from '@/components/ui/image';
export const statusLabels = {draft:'Чернетка',script_ready:'Сценарій готовий',audio_ready:'Озвучка готова',visual_ready:'Візуал готовий',ready:'Готове до перегляду',approved:'Погоджено',error:'Потрібна увага',running:'Створення…'};
export default function VideoList({videos=[],loading=false}) {
 if(loading) return <div className="panel p-12 text-center text-muted-foreground">Завантаження бібліотеки…</div>;
 if(!videos.length) return <div className="panel flex flex-col items-center justify-center min-h-[235px] p-6 text-center"><span className="empty-icon"><Film size={25} strokeWidth={1.3}/></span><h3 className="mt-4 text-sm font-medium">Тут почнеться ваша історія</h3><p className="text-xs text-muted-foreground mt-2 max-w-sm leading-relaxed">Створіть перший сценарій. Усі матеріали та етапи роботи збережуться в бібліотеці.</p><Link to="/studio" className="text-violet-300 text-xs inline-flex gap-2 items-center mt-5"><Plus size={14}/>Створити перший матеріал</Link></div>;
 return <div className="panel divide-y divide-white/[.06]">{videos.map(v=><Link key={v.id} to={`/studio?id=${v.id}`} className="flex gap-4 items-center p-4 hover:bg-white/[.025] transition-colors"><div className="h-14 w-10 rounded-md bg-violet-400/10 overflow-hidden flex-shrink-0 grid place-items-center">{v.image_url?<Image src={v.image_url} className="w-full h-full" alt="Візуал ролика"/>:<Film size={18} className="text-violet-300"/>}</div><div className="flex-1 min-w-0"><h3 className="text-sm truncate">{v.title}</h3><p className="text-xs text-muted-foreground mt-1">{v.duration ||30} сек · {v.language?.toUpperCase()} · 9:16</p></div><span className={`status-tag ${v.status==='error'?'text-rose-300':'text-violet-200'}`}>{statusLabels[v.status]||'Чернетка'}</span><ArrowUpRight className="hidden sm:block text-muted-foreground" size={17}/></Link>)}</div>;
}